name: flutter_google_maps
version: 4.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_polyline_algorithm: ^2.0.0
  google_maps_flutter: ^0.5.28+1
  google_directions_api: ^0.5.0
  google_maps: ^3.4.3
  http: ^0.12.0+1
  flinq: ^1.1.0
  uuid: ^2.1.0
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/marker_a.png
    - assets/images/marker_b.png